import numpy as np, matplotlib.pyplot as plt

x,v,m,D = np.load('opg8.npy')
t,psi = np.load('opg8t.npy')
xc = -2.5e-3
D = np.array([np.nonzero(D[i]) for i in xrange(len(D))])
D = np.array([D[i][0][-52:-1] for i in xrange(len(D))])
D = np.diff(D)
#psi = 6.0e-4
plt.subplot(2,1,1)
plt.plot(t,x[25]*1e3)
plt.title('$\psi = 6*10^{-4}$')
plt.ylabel('Posisjon [mm]')
plt.axis([0,20,0,-2.5])
plt.gca().invert_yaxis()
#psi = 6.3e-4
plt.subplot(2,1,2)
plt.plot(t,x[40]*1e3)
plt.title('$\psi = 6.3*10^{-4}$')
plt.xlabel('Tid [s]')
plt.ylabel('Posisjon [mm]')
plt.axis([0,20,0,-2.5])
plt.gca().invert_yaxis()
plt.savefig('psier.png')
#psi = 6.5e-4
plt.figure()
plt.subplot(2,1,1)
plt.plot(t,x[50]*1e3)
plt.title('$\psi = 6.5*10^{-4}$')
plt.ylabel('Posisjon [mm]')
plt.axis([0,20,0,-2.5])
plt.gca().invert_yaxis()
#psi = 7.3e-4
plt.subplot(2,1,2)
plt.plot(t,x[90]*1e3)
plt.title('$\psi = 7.3*10^{-4}$')
plt.xlabel('Tid [s]')
plt.ylabel('Posisjon [mm]')
plt.axis([0,20,0,-2.5])
plt.gca().invert_yaxis()
plt.savefig('psier1.png')
#psi plottet mot tidsforskjellen mellom hver draape
plt.figure()
plt.plot(psi,D/2000.0,'.')
plt.xlabel('$\psi$[kg/s]')
plt.ylabel('Tidsforskjell [s]')
plt.title('$\psi$ mot tidsforskjell naar draapen faller')
plt.savefig('psivsdt.png')
plt.show()
